media: media
content:
  - name: posts
    label: Blog Bricks
    type: file
    path: posts.json
    format: json
    list: true
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: content
        label: The Brick (Content)
        type: text
      - name: slug
        label: URL Slug (e.g. my-post)
        type: string
